# Generated by Django 3.2.5 on 2021-07-21 17:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default='f', max_length=1, verbose_name='Gender')),
                ('age', models.IntegerField(default=-1, verbose_name='Age')),
                ('dob', models.DateField(default=django.utils.timezone.now, verbose_name='Date of Birth')),
            ],
        ),
    ]
