# Generated by Django 3.2.5 on 2021-07-29 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formss', '0002_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Blog Title')),
                ('blog', models.TextField(verbose_name='Write whatever your what to say')),
            ],
        ),
        migrations.AlterField(
            model_name='persondetails',
            name='age',
            field=models.PositiveIntegerField(default=0, verbose_name='Age'),
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now=True, verbose_name='Date Posted')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formss.blog')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formss.person')),
            ],
        ),
    ]
