# Generated by Django 3.1.3 on 2021-04-16 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directory',
            name='booked_by',
            field=models.CharField(default='self', max_length=50),
            preserve_default=False,
        ),
    ]
