# Generated by Django 3.1.3 on 2021-05-03 09:42

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('media', models.FileField(upload_to=app.models.user_directory_path)),
            ],
        ),
    ]
