# Generated by Django 3.1.3 on 2021-05-05 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advisor_userid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(default=1)),
                ('date', models.DateTimeField()),
                ('advisor', models.ManyToManyField(to='app.Advisor')),
            ],
        ),
    ]
