# Generated by Django 3.1.3 on 2021-05-05 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_calls'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calls',
            name='advisor',
        ),
        migrations.AddField(
            model_name='calls',
            name='advisor',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='calls',
            name='date',
            field=models.DateTimeField(default='2021 May 05 13:33'),
        ),
    ]
